In [1]:
import numpy as np

In [2]:
List1 = [12, 24, 65 , 19, 242]
print(List1)

[12, 24, 65, 19, 242]


In [3]:
List2 = List1[0:4]
print(List2)

[12, 24, 65, 19]


In [4]:
List2[0] = 15

In [5]:
# Notice that while we changed a value in List2, the value in List2 remains the same
# The 2 lists are independent of one another
print("List1 contains: ", List1)
print("List2 contains: ", List2)

List1 contains:  [12, 24, 65, 19, 242]
List2 contains:  [15, 24, 65, 19]


In [6]:
Array1 = np.array(List1)
print(Array1)

[ 12  24  65  19 242]


In [7]:
Array2 = Array1[0:4]
print(Array2)

[12 24 65 19]


In [8]:
Array2[0] = 15

In [9]:
# Notice that because Array2 came from Array1, they are joined at the hip, so when you change
# the value in one, the value in the other immediately changes too!
print("Array1 contains: ", Array1)
print("Array2 contains: ", Array2)

Array1 contains:  [ 15  24  65  19 242]
Array2 contains:  [15 24 65 19]


In [10]:
Array1 = np.array(List1)
print(Array1)

[ 12  24  65  19 242]


In [11]:
# If this is not the desired effect use .copy() to make an independent copy
Array2 = Array1[0:4].copy()
print(Array2)

[12 24 65 19]


In [12]:
Array2[0] = 15

In [13]:
# Notice now that although we changed a value in Array2, Array1 has remained unaffected
print("Array1 contains: ", Array1)
print("Array2 contains: ", Array2)

Array1 contains:  [ 12  24  65  19 242]
Array2 contains:  [15 24 65 19]


In [14]:
List1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
List_Table = np.reshape(List1, (3,3))
print(List_Table)
print(type(List_Table))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [16]:
print(List_Table[0,2])
print(List_Table[:,1])

3
[2 5 8]


In [17]:
#Object oriented programming

In [18]:
List1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
print(List1.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#We played Scrabble in Jan, Feb & Mar, here are the scores:

In [21]:
Lisa_Mitford = [108, 215, 99]
Barry_Benjamin = [260, 212, 220]
Geoff_Louw = [176, 98, 232]
Denise_Louw = [102, 89, 276]

In [22]:
#Insert this lot into an array

In [23]:
Scores = np.array([Lisa_Mitford, Barry_Benjamin, Geoff_Louw, Denise_Louw])
print(Scores)

[[108 215  99]
 [260 212 220]
 [176  98 232]
 [102  89 276]]


In [24]:
#Create a player dictionary

In [25]:
PDict = {'Lisa_Mitford':0, 'Barry_Benjamin':1, 'Geoff_Louw':2, 'Denise_Louw':3}

In [26]:
#Create a months dictionary
MDict = {'Jan':0, 'Feb':1, 'Mar':2}

In [27]:
#To retrieve an individual item from the matrix

In [28]:
print(Scores[PDict['Geoff_Louw'], MDict['Mar']])

232


In [29]:
#To retrieve a whole row from the matrix

In [30]:
print(Scores[PDict['Geoff_Louw']])

[176  98 232]


In [31]:
#Or to retrieve a whole column from the matrix
print(Scores[:,MDict['Mar']])

[ 99 220 232 276]
